name: Deploy dot-hub to cf-workers
on: push

jobs:
  deploy:
    name: "Deploy dot-hub to cf-workers"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: dapp

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build & Deploy to NuxtHub
        uses: nuxt-hub/action@v2
        with:
          project-key: dot-hub-yn6r
          directory: dapp
